# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - uses: burrunan/gradle-cache-action@v1
      name: Build
      with:
        arguments: build
        gradle-version: wrapper
        properties: |
          kotlin.js.compiler=ir
          kotlin.parallel.tasks.in.project=true
    - name: Run codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./build/reports/jacoco/report.xml
